### ISSUE TITLE
Receiver not really receiving anything

### ISSUE THREAD

**Issue by brandonros** [minghuaw/fe2o3-amqp#264] opened 2024-08-03 04:03 UTC
I would expect a `Transfer` but I just see this:

```
RECV frame=Frame { channel: 0, body: Flow(Flow { next_incoming_id: Some(0), incoming_window: 5000, next_outgoing_id: 1, outgoing_window: 5000, handle: Some(Handle(1)), delivery_count: Some(0), link_credit: Some(0), available: Some(1), drain: false, echo: true, properties: None }) }
```

`available: Some(1)`

Am I misunderstanding something? I tried all of the "do not filter out, accept everything" code but I still don't get the message / delivery I want?

**Comment by minghuaw** [comment] 2024-08-04 00:52
Apparently the link credit is `0`, and there is one message waiting. Do you see any outbound `Flow` performatives that carry non-zero link credit in the logs?

**Comment by brandonros** [comment] 2024-08-04 00:57
the server is setting the link credit to 0. before this it was 200 or 1000. does that sound plausible?

**Comment by minghuaw** [comment] 2024-08-04 01:09
This shouldn't happen though. The specs states that only the receiver can independently change this value. (http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-flow)

**Comment by minghuaw** [comment] 2024-08-04 01:14
Do you see any outbound `Flow` frame in the logs?

**Comment by minghuaw** [comment] 2024-08-06 19:24
Closing as the cause of the problem is #267

**Closed by minghuaw** 2024-08-06 19:24 UTC

**Comment by brandonros** [comment] 2024-08-06 20:06
can you re-open for tracking please?

https://github.com/minghuaw/fe2o3-amqp/pull/263 is more important than you realize i think. not being able to set `open container frame` domain host different than connection string host will block usage for this usecase
